type Item = {
  name: string;
  type: string;
  rarity: string;
  levelRequirement: number;
  areaAssociation: string;
  attributesAndStats: {
    [key: string]: string;
  };
  loreTags: string[];
};

export const fantasyRpgItems: Item[] = [
  {
    name: "Demonic Elixir of Sunken City",
    type: "Potion (Elixir)",
    rarity: "Uncommon",
    levelRequirement: 4,
    areaAssociation: "Sky Isles",
    attributesAndStats: {
      manaRecovery: "+27",
      Healing: "+28",
    },
    loreTags: ["Guardian"],
  },
  {
    name: "Dragon Staff of Sunken City",
    type: "Weapon (Staff)",
    rarity: "Common",
    levelRequirement: 7,
    areaAssociation: "Forgotten Ruins",
    attributesAndStats: {
      attackSpeed: "+18",
      criticalHitChance: "+16",
    },
    loreTags: ["Warrior", "Celestial", "Ice"],
  },
  {
    name: "Wind Stamina Potion of Mystic Mountains",
    type: "Potion (Stamina Potion)",
    rarity: "Rare",
    levelRequirement: 38,
    areaAssociation: "Crystal Shores",
    attributesAndStats: {
      staminaBoost: "+26",
      manaRecovery: "+33",
    },
    loreTags: ["Water", "Mage"],
  },
  {
    name: "Nature Chestplate of Sunken City",
    type: "Armor (Chestplate)",
    rarity: "Common",
    levelRequirement: 47,
    areaAssociation: "Sunken City",
    attributesAndStats: {
      Defense: "+7",
      elementalResistance: "+21",
    },
    loreTags: ["Nature", "Stealth", "Lightning"],
  },
  {
    name: "Healing Belt of Enchanted Forest",
    type: "Accessory (Belt)",
    rarity: "Legendary",
    levelRequirement: 32,
    areaAssociation: "Frozen Tundra",
    attributesAndStats: {
      Fortitude: "+8",
      Charm: "+45",
    },
    loreTags: ["Light"],
  },
  {
    name: "Wind Spear of Ancient Library",
    type: "Weapon (Spear)",
    rarity: "Legendary",
    levelRequirement: 16,
    areaAssociation: "Ancient Library",
    attributesAndStats: {
      criticalHitChance: "+29",
      Damage: "+19",
    },
    loreTags: ["Light", "Elemental", "Mystic"],
  },
  {
    name: "Nature Leggings of Haunted Marshes",
    type: "Armor (Leggings)",
    rarity: "Rare",
    levelRequirement: 27,
    areaAssociation: "Sunken City",
    attributesAndStats: {
      Health: "+31",
      Defense: "+30",
    },
    loreTags: ["Mage", "Dragon"],
  },
  {
    name: "Light Necklace of Mystic Mountains",
    type: "Accessory (Necklace)",
    rarity: "Common",
    levelRequirement: 37,
    areaAssociation: "Forgotten Ruins",
    attributesAndStats: {
      Charm: "+20",
      Fortitude: "+20",
    },
    loreTags: ["Shadow", "Elemental"],
  },
  {
    name: "Poison Scroll of Volcanic Wastelands",
    type: "Artifact (Scroll)",
    rarity: "Common",
    levelRequirement: 50,
    areaAssociation: "Enchanted Forest",
    attributesAndStats: {
      Luck: "+33",
      magicPower: "+35",
    },
    loreTags: ["Celestial", "Summoner", "Darkness"],
  },
  {
    name: "Mystic Talisman of Volcanic Wastelands",
    type: "Artifact (Talisman)",
    rarity: "Epic",
    levelRequirement: 31,
    areaAssociation: "Dark Caves",
    attributesAndStats: {
      cooldownReduction: "+33",
      magicPower: "+7",
    },
    loreTags: ["Shadow"],
  },
  {
    name: "Summoner Gloves of Volcanic Wastelands",
    type: "Accessory (Gloves)",
    rarity: "Epic",
    levelRequirement: 6,
    areaAssociation: "Volcanic Wastelands",
    attributesAndStats: {
      Charm: "+49",
      Fortitude: "+46",
    },
    loreTags: ["Demonic", "Nature", "Assassin"],
  },
  {
    name: "Ancient Helmet of Dark Caves",
    type: "Armor (Helmet)",
    rarity: "Uncommon",
    levelRequirement: 49,
    areaAssociation: "Desert of Desolation",
    attributesAndStats: {
      Defense: "+38",
      Health: "+12",
    },
    loreTags: ["Wind", "Ice", "Demonic"],
  },
  {
    name: "Poison Health Potion of Whispering Woods",
    type: "Potion (Health Potion)",
    rarity: "Rare",
    levelRequirement: 7,
    areaAssociation: "Sunken City",
    attributesAndStats: {
      Healing: "+41",
      staminaBoost: "+44",
    },
    loreTags: ["Poison", "Stealth"],
  },
  {
    name: "Mystic Boots of Enchanted Forest",
    type: "Armor (Boots)",
    rarity: "Legendary",
    levelRequirement: 49,
    areaAssociation: "Whispering Woods",
    attributesAndStats: {
      Defense: "+12",
      Health: "+47",
    },
    loreTags: ["Healing", "Beast", "Ranger"],
  },
  {
    name: "Ice Ring of Whispering Woods",
    type: "Artifact (Ring)",
    rarity: "Legendary",
    levelRequirement: 25,
    areaAssociation: "Volcanic Wastelands",
    attributesAndStats: {
      cooldownReduction: "+15",
      magicPower: "+38",
    },
    loreTags: ["Fire", "Ice"],
  },
  {
    name: "Fire Mana Potion of Crystal Shores",
    type: "Potion (Mana Potion)",
    rarity: "Uncommon",
    levelRequirement: 36,
    areaAssociation: "Crystal Shores",
    attributesAndStats: {
      manaRecovery: "+41",
      staminaBoost: "+25",
    },
    loreTags: ["Lightning", "Wind", "Mystic"],
  },
  {
    name: "Shadow Wand of Forgotten Ruins",
    type: "Weapon (Wand)",
    rarity: "Epic",
    levelRequirement: 48,
    areaAssociation: "Sunken City",
    attributesAndStats: {
      Damage: "+7",
      criticalHitChance: "+10",
    },
    loreTags: ["Summoner", "Shadow"],
  },
  {
    name: "Earth Bracelet of Mystic Mountains",
    type: "Accessory (Bracelet)",
    rarity: "Epic",
    levelRequirement: 19,
    areaAssociation: "Sky Isles",
    attributesAndStats: {
      Agility: "+49",
      Charm: "+11",
    },
    loreTags: ["Ranger", "Beast"],
  },
  {
    name: "Spirit Belt of Crystal Shores",
    type: "Accessory (Belt)",
    rarity: "Rare",
    levelRequirement: 31,
    areaAssociation: "Sunken City",
    attributesAndStats: {
      Charm: "+45",
      Fortitude: "+36",
    },
    loreTags: ["Stealth"],
  },
  {
    name: "Beast Crossbow of Frozen Tundra",
    type: "Weapon (Crossbow)",
    rarity: "Uncommon",
    levelRequirement: 6,
    areaAssociation: "Sunken City",
    attributesAndStats: {
      Damage: "+18",
      attackSpeed: "+28",
    },
    loreTags: ["Time"],
  },
  {
    name: "Mystic Sword of Crystal Shores",
    type: "Weapon (Sword)",
    rarity: "Epic",
    levelRequirement: 37,
    areaAssociation: "Shadow Realm",
    attributesAndStats: {
      attackSpeed: "+12",
      criticalHitChance: "+31",
    },
    loreTags: ["Elemental"],
  },
  {
    name: "Spirit Amulet of Dark Caves",
    type: "Artifact (Amulet)",
    rarity: "Uncommon",
    levelRequirement: 19,
    areaAssociation: "Crystal Shores",
    attributesAndStats: {
      Luck: "+32",
      magicPower: "+22",
    },
    loreTags: ["Light", "Nature", "Celestial"],
  },
  {
    name: "Mystic Health Potion of Shadow Realm",
    type: "Potion (Health Potion)",
    rarity: "Common",
    levelRequirement: 38,
    areaAssociation: "Crystal Shores",
    attributesAndStats: {
      staminaBoost: "+5",
      Healing: "+44",
    },
    loreTags: ["Stealth"],
  },
  {
    name: "Mage Hammer of Shadow Realm",
    type: "Weapon (Hammer)",
    rarity: "Uncommon",
    levelRequirement: 18,
    areaAssociation: "Whispering Woods",
    attributesAndStats: {
      criticalHitChance: "+36",
      attackSpeed: "+48",
    },
    loreTags: ["Ice", "Elemental"],
  },
  {
    name: "Light Shield of Mystic Mountains",
    type: "Armor (Shield)",
    rarity: "Rare",
    levelRequirement: 41,
    areaAssociation: "Enchanted Forest",
    attributesAndStats: {
      Health: "+5",
      elementalResistance: "+25",
    },
    loreTags: ["Warrior", "Dragon", "Ice"],
  },
  {
    name: "Ancient Ring of Mystic Mountains",
    type: "Artifact (Ring)",
    rarity: "Common",
    levelRequirement: 37,
    areaAssociation: "Volcanic Wastelands",
    attributesAndStats: {
      magicPower: "+45",
      cooldownReduction: "+43",
    },
    loreTags: ["Shadow", "Undead", "Guardian"],
  },
  {
    name: "Warrior Ring of Shadow Realm",
    type: "Artifact (Ring)",
    rarity: "Common",
    levelRequirement: 17,
    areaAssociation: "Sky Isles",
    attributesAndStats: {
      cooldownReduction: "+45",
      magicPower: "+38",
    },
    loreTags: ["Wind", "Lightning"],
  },
  {
    name: "Undead Sword of Celestial Towers",
    type: "Weapon (Sword)",
    rarity: "Uncommon",
    levelRequirement: 21,
    areaAssociation: "Desert of Desolation",
    attributesAndStats: {
      attackSpeed: "+11",
      Damage: "+34",
    },
    loreTags: ["Mage"],
  },
  {
    name: "Darkness Leggings of Volcanic Wastelands",
    type: "Armor (Leggings)",
    rarity: "Epic",
    levelRequirement: 4,
    areaAssociation: "Mystic Mountains",
    attributesAndStats: {
      elementalResistance: "+30",
      Health: "+34",
    },
    loreTags: ["Wind", "Guardian", "Demonic"],
  },
  {
    name: "Mage Spear of Desert of Desolation",
    type: "Weapon (Spear)",
    rarity: "Legendary",
    levelRequirement: 15,
    areaAssociation: "Forgotten Ruins",
    attributesAndStats: {
      criticalHitChance: "+38",
      Damage: "+30",
    },
    loreTags: ["Undead", "Shadow"],
  },
  {
    name: "Dragon Earrings of Haunted Marshes",
    type: "Accessory (Earrings)",
    rarity: "Epic",
    levelRequirement: 28,
    areaAssociation: "Shadow Realm",
    attributesAndStats: {
      Fortitude: "+22",
      Agility: "+12",
    },
    loreTags: ["Assassin", "Nature"],
  },
  {
    name: "Lightning Necklace of Dark Caves",
    type: "Accessory (Necklace)",
    rarity: "Common",
    levelRequirement: 10,
    areaAssociation: "Whispering Woods",
    attributesAndStats: {
      Agility: "+21",
      Charm: "+24",
    },
    loreTags: ["Ice", "Mystic"],
  },
  {
    name: "Warrior Strength Potion of Sunken City",
    type: "Potion (Strength Potion)",
    rarity: "Rare",
    levelRequirement: 45,
    areaAssociation: "Sky Isles",
    attributesAndStats: {
      manaRecovery: "+35",
      staminaBoost: "+37",
    },
    loreTags: ["Mage"],
  },
  {
    name: "Water Orb of Whispering Woods",
    type: "Artifact (Orb)",
    rarity: "Uncommon",
    levelRequirement: 8,
    areaAssociation: "Volcanic Wastelands",
    attributesAndStats: {
      magicPower: "+44",
      cooldownReduction: "+36",
    },
    loreTags: ["Assassin", "Mage", "Demonic"],
  },
  {
    name: "Nature Orb of Crystal Shores",
    type: "Artifact (Orb)",
    rarity: "Common",
    levelRequirement: 3,
    areaAssociation: "Enchanted Forest",
    attributesAndStats: {
      Luck: "+10",
      magicPower: "+48",
    },
    loreTags: ["Mystic"],
  },
  {
    name: "Ice Gloves of Dark Caves",
    type: "Accessory (Gloves)",
    rarity: "Common",
    levelRequirement: 12,
    areaAssociation: "Volcanic Wastelands",
    attributesAndStats: {
      Charm: "+42",
      Agility: "+13",
    },
    loreTags: ["Undead", "Light", "Guardian"],
  },
  {
    name: "Water Shield of Volcanic Wastelands",
    type: "Armor (Shield)",
    rarity: "Rare",
    levelRequirement: 23,
    areaAssociation: "Sky Isles",
    attributesAndStats: {
      Health: "+49",
      Defense: "+43",
    },
    loreTags: ["Nature", "Healing", "Fire"],
  },
  {
    name: "Assassin Relic of Desert of Desolation",
    type: "Artifact (Relic)",
    rarity: "Epic",
    levelRequirement: 10,
    areaAssociation: "Crystal Shores",
    attributesAndStats: {
      cooldownReduction: "+34",
      magicPower: "+46",
    },
    loreTags: ["Nature", "Elemental"],
  },
  {
    name: "Celestial Orb",
    type: "Artifact (Relic)",
    rarity: "Epic",
    levelRequirement: 29,
    areaAssociation: "Sky Isles",
    attributesAndStats: {
      Healing: "+29",
      manaRecovery: "+27",
    },
    loreTags: ["Ice", "Dragon", "Ancient"],
  },
  {
    name: "Celestial Invisibility Potion of Mystic Mountains",
    type: "Potion (Invisibility Potion)",
    rarity: "Epic",
    levelRequirement: 19,
    areaAssociation: "Forgotten Ruins",
    attributesAndStats: {
      staminaBoost: "+46",
      Healing: "+7",
    },
    loreTags: ["Water"],
  },
  {
    name: "Nature Crystal of Mystic Mountains",
    type: "Artifact (Crystal)",
    rarity: "Rare",
    levelRequirement: 11,
    areaAssociation: "Volcanic Wastelands",
    attributesAndStats: {
      magicPower: "+37",
      Luck: "+48",
    },
    loreTags: ["Time"],
  },
  {
    name: "Ice Hammer of Enchanted Forest",
    type: "Weapon (Hammer)",
    rarity: "Common",
    levelRequirement: 45,
    areaAssociation: "Desert of Desolation",
    attributesAndStats: {
      attackSpeed: "+20",
      Damage: "+34",
    },
    loreTags: ["Wind", "Fire"],
  },
  {
    name: "Spirit Earrings of Mystic Mountains",
    type: "Accessory (Earrings)",
    rarity: "Legendary",
    levelRequirement: 27,
    areaAssociation: "Crystal Shores",
    attributesAndStats: {
      Agility: "+5",
      Charm: "+47",
    },
    loreTags: ["Poison"],
  },
  {
    name: "Darkness Talisman of Sky Isles",
    type: "Artifact (Talisman)",
    rarity: "Common",
    levelRequirement: 3,
    areaAssociation: "Sky Isles",
    attributesAndStats: {
      magicPower: "+13",
      Luck: "+13",
    },
    loreTags: ["Shadow", "Nature", "Spirit"],
  },
  {
    name: "Healing Spear of Desert of Desolation",
    type: "Weapon (Spear)",
    rarity: "Epic",
    levelRequirement: 26,
    areaAssociation: "Sunken City",
    attributesAndStats: {
      criticalHitChance: "+45",
      attackSpeed: "+40",
    },
    loreTags: ["Spirit", "Warrior", "Undead"],
  },
  {
    name: "Time Mana Potion of Crystal Shores",
    type: "Potion (Mana Potion)",
    rarity: "Common",
    levelRequirement: 46,
    areaAssociation: "Frozen Tundra",
    attributesAndStats: {
      Healing: "+29",
      staminaBoost: "+13",
    },
    loreTags: ["Dragon", "Beast"],
  },
  {
    name: "Light Amulet of Celestial Towers",
    type: "Artifact (Amulet)",
    rarity: "Legendary",
    levelRequirement: 31,
    areaAssociation: "Mystic Mountains",
    attributesAndStats: {
      magicPower: "+48",
      cooldownReduction: "+41",
    },
    loreTags: ["Ice", "Mage"],
  },
  {
    name: "Celestial Leggings of Whispering Woods",
    type: "Armor (Leggings)",
    rarity: "Legendary",
    levelRequirement: 26,
    areaAssociation: "Whispering Woods",
    attributesAndStats: {
      Health: "+6",
      elementalResistance: "+26",
    },
    loreTags: ["Mystic", "Mage", "Dragon"],
  },
  {
    name: "Celestial Defense Potion of Mystic Mountains",
    type: "Potion (Defense Potion)",
    rarity: "Rare",
    levelRequirement: 44,
    areaAssociation: "Celestial Towers",
    attributesAndStats: {
      manaRecovery: "+40",
      Healing: "+36",
    },
    loreTags: ["Mystic", "Earth", "Healing"],
  },
  {
    name: "Summoner Relic of Haunted Marshes",
    type: "Artifact (Relic)",
    rarity: "Common",
    levelRequirement: 13,
    areaAssociation: "Enchanted Forest",
    attributesAndStats: {
      Luck: "+6",
      cooldownReduction: "+50",
    },
    loreTags: ["Ranger"],
  },
  {
    name: "Wind Boots of Sunken City",
    type: "Armor (Boots)",
    rarity: "Epic",
    levelRequirement: 34,
    areaAssociation: "Enchanted Forest",
    attributesAndStats: {
      elementalResistance: "+32",
      Defense: "+40",
    },
    loreTags: ["Dragon", "Poison"],
  },
  {
    name: "Beast Amulet of Sunken City",
    type: "Artifact (Amulet)",
    rarity: "Common",
    levelRequirement: 4,
    areaAssociation: "Crystal Shores",
    attributesAndStats: {
      magicPower: "+47",
      cooldownReduction: "+7",
    },
    loreTags: ["Poison", "Dragon"],
  },
  {
    name: "Shadow Gauntlets of Mystic Mountains",
    type: "Armor (Gauntlets)",
    rarity: "Common",
    levelRequirement: 46,
    areaAssociation: "Celestial Towers",
    attributesAndStats: {
      Health: "+22",
      elementalResistance: "+15",
    },
    loreTags: ["Elemental", "Mystic", "Light"],
  },
  {
    name: "Wind Health Potion of Sunken City",
    type: "Potion (Health Potion)",
    rarity: "Legendary",
    levelRequirement: 50,
    areaAssociation: "Enchanted Forest",
    attributesAndStats: {
      Healing: "+24",
      manaRecovery: "+25",
    },
    loreTags: ["Lightning"],
  },
  {
    name: "Ranger Rune of Frozen Tundra",
    type: "Artifact (Rune)",
    rarity: "Legendary",
    levelRequirement: 39,
    areaAssociation: "Whispering Woods",
    attributesAndStats: {
      magicPower: "+32",
      cooldownReduction: "+28",
    },
    loreTags: ["Warrior", "Celestial"],
  },
  {
    name: "Wind Leggings of Enchanted Forest",
    type: "Armor (Leggings)",
    rarity: "Legendary",
    levelRequirement: 21,
    areaAssociation: "Sunken City",
    attributesAndStats: {
      elementalResistance: "+21",
      Health: "+35",
    },
    loreTags: ["Healing", "Celestial"],
  },
  {
    name: "Beast Talisman of Sunken City",
    type: "Artifact (Talisman)",
    rarity: "Epic",
    levelRequirement: 47,
    areaAssociation: "Whispering Woods",
    attributesAndStats: {
      Luck: "+29",
      cooldownReduction: "+19",
    },
    loreTags: ["Celestial"],
  },
  {
    name: "Spirit Axe of Forgotten Ruins",
    type: "Weapon (Axe)",
    rarity: "Uncommon",
    levelRequirement: 23,
    areaAssociation: "Desert of Desolation",
    attributesAndStats: {
      attackSpeed: "+49",
      criticalHitChance: "+18",
    },
    loreTags: ["Lightning", "Mage", "Spirit"],
  },
  {
    name: "Time Orb of Desert of Desolation",
    type: "Artifact (Orb)",
    rarity: "Common",
    levelRequirement: 17,
    areaAssociation: "Sunken City",
    attributesAndStats: {
      magicPower: "+28",
      Luck: "+37",
    },
    loreTags: ["Light", "Demonic"],
  },
  {
    name: "Assassin Stamina Potion of Shadow Realm",
    type: "Potion (Stamina Potion)",
    rarity: "Legendary",
    levelRequirement: 45,
    areaAssociation: "Enchanted Forest",
    attributesAndStats: {
      staminaBoost: "+6",
      manaRecovery: "+26",
    },
    loreTags: ["Dragon", "Mage", "Time"],
  },
  {
    name: "Warrior Shield of Crystal Shores",
    type: "Armor (Shield)",
    rarity: "Rare",
    levelRequirement: 1,
    areaAssociation: "Haunted Marshes",
    attributesAndStats: {
      Defense: "+30",
      elementalResistance: "+11",
    },
    loreTags: ["Fire", "Stealth", "Ice"],
  },
  {
    name: "Mystic Boots of Sky Isles",
    type: "Armor (Boots)",
    rarity: "Common",
    levelRequirement: 15,
    areaAssociation: "Crystal Shores",
    attributesAndStats: {
      Health: "+45",
      Defense: "+43",
    },
    loreTags: ["Ice", "Ancient"],
  },
  {
    name: "Wind Strength Potion of Mystic Mountains",
    type: "Potion (Strength Potion)",
    rarity: "Rare",
    levelRequirement: 27,
    areaAssociation: "Haunted Marshes",
    attributesAndStats: {
      staminaBoost: "+7",
      manaRecovery: "+33",
    },
    loreTags: ["Mage", "Nature"],
  },
  {
    name: "Ice Orb of Frozen Tundra",
    type: "Artifact (Orb)",
    rarity: "Legendary",
    levelRequirement: 33,
    areaAssociation: "Sky Isles",
    attributesAndStats: {
      magicPower: "+22",
      Luck: "+24",
    },
    loreTags: ["Ancient", "Mage"],
  },
  {
    name: "Wind Gauntlets of Celestial Towers",
    type: "Armor (Gauntlets)",
    rarity: "Legendary",
    levelRequirement: 25,
    areaAssociation: "Ancient Library",
    attributesAndStats: {
      elementalResistance: "+30",
      Defense: "+13",
    },
    loreTags: ["Water"],
  },
  {
    name: "Lightning Brooch of Whispering Woods",
    type: "Accessory (Brooch)",
    rarity: "Epic",
    levelRequirement: 19,
    areaAssociation: "Celestial Towers",
    attributesAndStats: {
      Agility: "+42",
      Fortitude: "+48",
    },
    loreTags: ["Nature"],
  },
  {
    name: "Elemental Necklace of Haunted Marshes",
    type: "Accessory (Necklace)",
    rarity: "Common",
    levelRequirement: 13,
    areaAssociation: "Desert of Desolation",
    attributesAndStats: {
      Charm: "+34",
      Agility: "+43",
    },
    loreTags: ["Darkness", "Fire", "Ranger"],
  },
  {
    name: "Ice Leggings of Sunken City",
    type: "Armor (Leggings)",
    rarity: "Uncommon",
    levelRequirement: 17,
    areaAssociation: "Sunken City",
    attributesAndStats: {
      Health: "+24",
      elementalResistance: "+40",
    },
    loreTags: ["Ice", "Time"],
  },
  {
    name: "Mage Robes of Enchanted Forest",
    type: "Armor (Robes)",
    rarity: "Common",
    levelRequirement: 42,
    areaAssociation: "Enchanted Forest",
    attributesAndStats: {
      Defense: "+38",
      Health: "+8",
    },
    loreTags: ["Darkness", "Undead", "Beast"],
  },
  {
    name: "Ancient Robes of Crystal Shores",
    type: "Armor (Robes)",
    rarity: "Common",
    levelRequirement: 5,
    areaAssociation: "Shadow Realm",
    attributesAndStats: {
      Defense: "+13",
      elementalResistance: "+22",
    },
    loreTags: ["Undead", "Beast"],
  },
  {
    name: "Birchwood Staff",
    type: "Weapon (Staff)",
    rarity: "Epic",
    levelRequirement: 8,
    areaAssociation: "Enchanted Forest",
    attributesAndStats: {
      manaRecovery: "+43",
      Healing: "+21",
    },
    loreTags: ["Ice", "Summoner"],
  },
  {
    name: "Water Gloves of Enchanted Forest",
    type: "Accessory (Gloves)",
    rarity: "Common",
    levelRequirement: 35,
    areaAssociation: "Crystal Shores",
    attributesAndStats: {
      Fortitude: "+16",
      Agility: "+42",
    },
    loreTags: ["Spirit", "Nature", "Fire"],
  },
  {
    name: "Dragon Dagger of Enchanted Forest",
    type: "Weapon (Dagger)",
    rarity: "Uncommon",
    levelRequirement: 22,
    areaAssociation: "Sky Isles",
    attributesAndStats: {
      attackSpeed: "+9",
      Damage: "+19",
    },
    loreTags: ["Demonic"],
  },
  {
    name: "Nature Rune of Shadow Realm",
    type: "Artifact (Rune)",
    rarity: "Common",
    levelRequirement: 50,
    areaAssociation: "Mystic Mountains",
    attributesAndStats: {
      magicPower: "+13",
      cooldownReduction: "+33",
    },
    loreTags: ["Ranger"],
  },
  {
    name: "Undead Spear of Ancient Library",
    type: "Weapon (Spear)",
    rarity: "Legendary",
    levelRequirement: 42,
    areaAssociation: "Shadow Realm",
    attributesAndStats: {
      Damage: "+40",
      attackSpeed: "+48",
    },
    loreTags: ["Summoner", "Shadow"],
  },
  {
    name: "Fire Stamina Potion of Mystic Mountains",
    type: "Potion (Stamina Potion)",
    rarity: "Common",
    levelRequirement: 11,
    areaAssociation: "Sky Isles",
    attributesAndStats: {
      manaRecovery: "+35",
      Healing: "+33",
    },
    loreTags: ["Light", "Dragon", "Warrior"],
  },
  {
    name: "Summoner Cloak of Ancient Library",
    type: "Armor (Cloak)",
    rarity: "Common",
    levelRequirement: 2,
    areaAssociation: "Frozen Tundra",
    attributesAndStats: {
      Health: "+30",
      Defense: "+48",
    },
    loreTags: ["Summoner", "Earth"],
  },
  {
    name: "Fire Earrings of Ancient Library",
    type: "Accessory (Earrings)",
    rarity: "Rare",
    levelRequirement: 48,
    areaAssociation: "Sky Isles",
    attributesAndStats: {
      Charm: "+12",
      Fortitude: "+10",
    },
    loreTags: ["Fire", "Ancient"],
  },
  {
    name: "Beast Axe of Dark Caves",
    type: "Weapon (Axe)",
    rarity: "Legendary",
    levelRequirement: 48,
    areaAssociation: "Crystal Shores",
    attributesAndStats: {
      criticalHitChance: "+32",
      Damage: "+45",
    },
    loreTags: ["Ranger", "Assassin"],
  },
  {
    name: "Ancient Gauntlets of Frozen Tundra",
    type: "Armor (Gauntlets)",
    rarity: "Uncommon",
    levelRequirement: 20,
    areaAssociation: "Crystal Shores",
    attributesAndStats: {
      Defense: "+26",
      Health: "+40",
    },
    loreTags: ["Light", "Healing"],
  },
  {
    name: "Mystic Brooch of Sky Isles",
    type: "Accessory (Brooch)",
    rarity: "Common",
    levelRequirement: 27,
    areaAssociation: "Sunken City",
    attributesAndStats: {
      Charm: "+44",
      Agility: "+29",
    },
    loreTags: ["Mage", "Stealth"],
  },
  {
    name: "Earth Gauntlets of Ancient Library",
    type: "Armor (Gauntlets)",
    rarity: "Rare",
    levelRequirement: 39,
    areaAssociation: "Ancient Library",
    attributesAndStats: {
      Health: "+24",
      Defense: "+18",
    },
    loreTags: ["Time", "Elemental", "Healing"],
  },
  {
    name: "Elemental Gauntlets of Haunted Marshes",
    type: "Armor (Gauntlets)",
    rarity: "Common",
    levelRequirement: 5,
    areaAssociation: "Sky Isles",
    attributesAndStats: {
      Health: "+21",
      elementalResistance: "+47",
    },
    loreTags: ["Ice"],
  },
  {
    name: "Warrior Mana Potion of Forgotten Ruins",
    type: "Potion (Mana Potion)",
    rarity: "Uncommon",
    levelRequirement: 45,
    areaAssociation: "Forgotten Ruins",
    attributesAndStats: {
      manaRecovery: "+8",
      Healing: "+22",
    },
    loreTags: ["Stealth"],
  },
  {
    name: "Ice Talisman of Dark Caves",
    type: "Artifact (Talisman)",
    rarity: "Uncommon",
    levelRequirement: 43,
    areaAssociation: "Desert of Desolation",
    attributesAndStats: {
      magicPower: "+43",
      cooldownReduction: "+39",
    },
    loreTags: ["Mystic", "Nature"],
  },
  {
    name: "Mage Robes of Forgotten Ruins",
    type: "Armor (Robes)",
    rarity: "Epic",
    levelRequirement: 31,
    areaAssociation: "Enchanted Forest",
    attributesAndStats: {
      elementalResistance: "+30",
      Defense: "+28",
    },
    loreTags: ["Ranger"],
  },
  {
    name: "Fire Belt of Haunted Marshes",
    type: "Accessory (Belt)",
    rarity: "Common",
    levelRequirement: 1,
    areaAssociation: "Dark Caves",
    attributesAndStats: {
      Fortitude: "+38",
      Charm: "+12",
    },
    loreTags: ["Ancient", "Undead", "Demonic"],
  },
  {
    name: "Ancient Boots of Ancient Library",
    type: "Armor (Boots)",
    rarity: "Common",
    levelRequirement: 7,
    areaAssociation: "Whispering Woods",
    attributesAndStats: {
      Defense: "+30",
      elementalResistance: "+46",
    },
    loreTags: ["Water", "Lightning", "Ranger"],
  },
  {
    name: "Ancient Scroll of Sky Isles",
    type: "Artifact (Scroll)",
    rarity: "Rare",
    levelRequirement: 1,
    areaAssociation: "Desert of Desolation",
    attributesAndStats: {
      Luck: "+44",
      cooldownReduction: "+29",
    },
    loreTags: ["Lightning"],
  },
  {
    name: "Time Cloak of Haunted Marshes",
    type: "Armor (Cloak)",
    rarity: "Legendary",
    levelRequirement: 9,
    areaAssociation: "Desert of Desolation",
    attributesAndStats: {
      Defense: "+27",
      Health: "+11",
    },
    loreTags: ["Celestial", "Healing"],
  },
  {
    name: "Mystic Ring of Forgotten Ruins",
    type: "Artifact (Ring)",
    rarity: "Rare",
    levelRequirement: 41,
    areaAssociation: "Sky Isles",
    attributesAndStats: {
      Luck: "+27",
      cooldownReduction: "+29",
    },
    loreTags: ["Ice", "Poison", "Shadow"],
  },
  {
    name: "Light Brooch of Haunted Marshes",
    type: "Accessory (Brooch)",
    rarity: "Rare",
    levelRequirement: 12,
    areaAssociation: "Haunted Marshes",
    attributesAndStats: {
      Agility: "+18",
      Fortitude: "+13",
    },
    loreTags: ["Light", "Elemental", "Wind"],
  },
  {
    name: "Earth Stamina Potion of Sky Isles",
    type: "Potion (Stamina Potion)",
    rarity: "Common",
    levelRequirement: 38,
    areaAssociation: "Celestial Towers",
    attributesAndStats: {
      manaRecovery: "+48",
      Healing: "+29",
    },
    loreTags: ["Assassin"],
  },
  {
    name: "Mage Bracelet of Whispering Woods",
    type: "Accessory (Bracelet)",
    rarity: "Uncommon",
    levelRequirement: 24,
    areaAssociation: "Celestial Towers",
    attributesAndStats: {
      Fortitude: "+18",
      Charm: "+24",
    },
    loreTags: ["Dragon", "Mystic", "Summoner"],
  },
  {
    name: "Assassin Relic of Enchanted Forest",
    type: "Artifact (Relic)",
    rarity: "Rare",
    levelRequirement: 41,
    areaAssociation: "Volcanic Wastelands",
    attributesAndStats: {
      magicPower: "+20",
      Luck: "+44",
    },
    loreTags: ["Stealth", "Light", "Celestial"],
  },
  {
    name: "Ranger Health Potion of Forgotten Ruins",
    type: "Potion (Health Potion)",
    rarity: "Common",
    levelRequirement: 44,
    areaAssociation: "Dark Caves",
    attributesAndStats: {
      Healing: "+24",
      manaRecovery: "+37",
    },
    loreTags: ["Fire", "Assassin", "Healing"],
  },
];

